[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true
language-servers = ["ty"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ty.config]
experimental.rename = true
experimental.autoImport = true
